### PR TITLE
tgui chat message stacking and message amount improvements

### LINKED ISSUE #23972: Duplicate messages no longer stack 100% of the time
### Exploit Reports

- [X] I confirm this issue is not an exploit. (Required)

### BYOND Version

515.1630

### Issue Description

Duplicate messages no longer stack 100% of the time. Seems rather arbitrary what they stack to as well. I've had some stack to 5 and some stack to 15

### What did you expect to happen?

Consistent behavior with all messages stacking

### What happened instead?

stuff

### Why is this bad/What are the consequences?

Inconsistent

### Steps to reproduce the issue.

Get a bunch of duplicate messages sent to you
Watch them not stack

### When did the problem start happening?

TGUIv4

### Extra information

_No response_

### Relevant log output/runtime error

_No response_

### PR DESCRIPTION
**Pull request by GDNgit**
## What Does This PR Do
TGchat stack expiration is now set by the user 
TGchat now holds 10k messages by default instead of 1k. TGchat message amounts can now be configured, maximum amount of messages is 25k

fixes #23972
## Why It's Good For The Game
Messages stacking within a more reasonable time frame is good. We use MS rather than DS for seconds in js. 
Tgchat should be able to hold more messages in a largely roleplay focused server considering you're almost certainly gonna need late stuff in there.
also customization good YIPPIE (No, we cannot use stacks here)

better

## Testing
made a function to spam my chat and ran it

## Changelog
:cl:
tweak: TGchat now stacks all duplicate messages that occur in a 30 second time window instead of a 5 second window by default. Can be configured in your chat settings (max 10 minutes)
tweak: TGchat now holds up to 10k messages instead of 1k. Can be configured in your chat settings (max 25k messages)
/:cl:

### CODE REVIEW

File: tgui/packages/tgui-panel/chat/constants.js [hunk 1]
```diff
@@ -5,11 +5,11 @@
  */
 
 export const MAX_VISIBLE_MESSAGES = 2500;
-export const MAX_PERSISTED_MESSAGES = 1000;
+export const MAX_PERSISTED_MESSAGES = 10000;
 export const MESSAGE_SAVE_INTERVAL = 10000;
 export const MESSAGE_PRUNE_INTERVAL = 60000;
 export const COMBINE_MAX_MESSAGES = 5;
-export const COMBINE_MAX_TIME_WINDOW = 5000;
+export const COMBINE_MAX_TIME_WINDOW = 50000;
```
Comment (CinnamonSnowball) [inline tgui/packages/tgui-panel/chat/constants.js:12]: > We use MS rather than DS for seconds in js.

Might be good to leave a comment here considering the confusion arose once already?

Comment (GDNgit) [reply tgui/packages/tgui-panel/chat/constants.js]: Put a comment there

Comment (Aylong220) [reply tgui/packages/tgui-panel/chat/constants.js]: 50 seconds? That's too much, old examine messages will stack if not changed

File: tgui/packages/tgui-panel/settings/reducer.js [hunk 2]
```diff
@@ -26,6 +26,8 @@ const initialState = {
   lineHeight: 1.2,
   theme: 'dark',
   adminMusicVolume: 0.5,
+  MessageStackInSeconds: 30,
+  MaxTotalMessage: 10000,
```
Comment (S34NW) [inline tgui/packages/tgui-panel/settings/reducer.js:30]:
```suggestion
  messageStackInSeconds: 30,
  maxTotalMessage: 10000,
```

js case styling is camelCase for identifier names (this will need to change in refs too)

Comment (GDNgit) [reply tgui/packages/tgui-panel/settings/reducer.js]: addressed
god i hate js

File: tgui/packages/tgui-panel/settings/SettingsPanel.js [hunk 3]
```diff
@@ -155,6 +160,20 @@ export const SettingsGeneral = (props, context) => {
               )
             }
           />
+          <Box inline fontSize="1em" mx={1} color="label">
+            Total messages displayed:
```
Comment (S34NW) [inline tgui/packages/tgui-panel/settings/SettingsPanel.js:164]:
```suggestion
            Maximum messages displayed:
```

Comment (S34NW) [reply tgui/packages/tgui-panel/settings/SettingsPanel.js:164]: other than that, good to go

**Review by S34NW — APPROVED** [review]
