### PR TITLE
Make hotspots go out easier.

### LINKED ISSUE #28014: Putting water on fires can make the air very cold
### Exploit Reports

- [x] I confirm this issue is not an exploit. (Required)

### BYOND Version

1645

### Issue Description

Spraying water from a fire extinguisher onto plasma fires sometimes causes the air to get super cold, like -12c cold

### What did you expect to happen?

air to be hot.

### What happened instead?

woops, airs now super cooled

### Why is this bad/What are the consequences?

Somewhat nullifies the heat worry of plasmafires, also can cause weird wind to happen, like a fire sucking in items around it, rather than pushing, and causing fires to make partal vacuumes 

### Steps to reproduce the issue.

not entirely sure, spraying water onto fires sometimes makes the air cold. its (seemingly) not all the time

### When did the problem start happening?

MILLA 2 

### Extra information

_No response_

### Relevant log output/runtime error

```DM

```

### LINKED ISSUE #28737: Fake plasma spawns out of nowhere, air itself is burning eternally.
### Exploit Reports

- [x] I confirm this issue is not an exploit. (Required)

### BYOND Version

515.1646

### Issue Description

After a blob spawned on Emerald, plasma overlay has started appearing over vents near the blob. The tiles did not contain any plasma but would ignite and the fire would spread, and continue to burn without using oxygen or nitrogen up. There was not a single trace of plasma in the distro and admins could not find any possible foul plays.

Image

### What did you expect to happen?

Nothing. I expected nothing of the sort happening at all.

### What happened instead?

The station was on permanent fire, the server hit time dilation 10% at one point.

### Why is this bad/What are the consequences?

It breaks the balance and the server itself. It also causes a lot of confusion and has dealt massive sanity damage to everyone watching it unfold.

### Steps to reproduce the issue.

Unknown.
Someone reported trying to weaponise a plasma canister against the blob and there was one empty undestroyed canister on the station. Vents seemed to spawn the "fake" plasma only when atmos over them was disturbed. Whether the blob was directly related to it or not, I don't know.

### When did the problem start happening?

20/03/2025.
According to the admin I asked to check for runtimes, they saw something similar yesterday.

### Extra information

I'm so confused I don't even know what to suspect. 

### Relevant log output/runtime error

```DM
n/a, admins claimed no atmos-related runtimes were logged.
```

### PR DESCRIPTION
**Pull request by FunnyMan3595**
## What Does This PR Do
Extinguishers correctly kill off the hotspot in MILLA, not just the DM-side one. Likely fixes #28014.
MILLA hotspots will now slowly conduct heat to their tile, preventing tiny reactions from perpetually keeping a tile on fire. Likely fixes #28737.

## Why It's Good For The Game
Fires should behave sensibly.

## Testing
Made burn mix. Added E-Ns. Sparks set burn mix on fire.
Made a burn mix tile contained in holofans, at high temperature. Applied extinguisher a few times. Tile cooled and stopped burning.
Filled an area with N2O. Walked around while on fire. No residual fires created.
Filled an area with N2O at high temperature. N2O decomposed.
Made burn mix at high temperature. Fired nanofrost at it. Reasonably effective.

## Declaration
- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.

## Changelog
:cl:
fix: Extingushers can put out MILLA hotspots (sub-tile fires).
fix: MILLA hotspots will die out if they're not burning fast enough.
/:cl:

### CODE REVIEW

**Comment by FunnyMan3595** [comment]
!build_rust

File: rust/src/milla/simulate.rs [hunk 1]
```diff
@@ -637,14 +637,22 @@ pub(crate) fn react(my_next_tile: &mut Tile, hotspot_step: bool) {
...
 
     if hotspot_step {
-        adjust_hotspot(my_next_tile, thermal_energy - initial_thermal_energy);
+        // Conduct some temperature to the tile.
+        let mut conduction = 0.0;
+        let tile_temperature = my_next_tile.temperature();
+        let temperature_difference = cached_temperature - tile_temperature;
+        if temperature_difference > 0.0 {
+            let excess_thermal_energy = temperature_difference * cached_heat_capacity;
+            conduction  = excess_thermal_energy * HOTSPOT_CONDUCTION;
```
Comment (lewcc) [inline rust/src/milla/simulate.rs:652]:
```suggestion
            conduction = excess_thermal_energy * HOTSPOT_CONDUCTION;
```

**Review by lewcc — APPROVED** [review]

**Review by Contrabang — APPROVED** [review]

**Comment by FunnyMan3595** [comment]
!build_rust
