### PR TITLE
Readds Atmos freezing to loading maps

### LINKED ISSUE #26385: Z-level manager no longer freezes atmos on dynamic map load
### Exploit Reports

- [X] I confirm this issue is not an exploit. (Required)

### BYOND Version

515.1641

### Issue Description

The space manager, a global `/datum/zlev_manager` used for managing z-levels and dynamic map loading, provides the `/datum/zlev_manager/proc/add_dirt(z)`, `/datum/zlev_manager/proc/remove_dirt(z)`, and `/datum/zlev_manager/proc/is_zlevel_dirty(z)` procs which are used to "freeze" initialization of atoms until the dirt count on a z-level is zero. This is used to prevent things like atmos from processing while a map is being loaded in dynamically. Frozen atoms are stored in a list for later initialization in `/datum/space_level/resume_init()`, which will deal building pipenets, cables, and beginning atmos processing.

Post-MILLA, this system no longer works as expected for freezing atmos.

### What did you expect to happen?

When loading shuttles or admin event ruins in, atmos should pause processing until the entire DMM is placed.

### What happened instead?

Atmos processing during ruin loading causes objects to move around unintentionally, and requires us to allow for maplint exclusions so that shuttles requiring proper post-dirt atmos processing do not have to pass lint checks, such as:

https://github.com/ParadiseSS13/Paradise/blob/6837ea7333aadfa7e09011bfc8fd806060c24340/tools/maplint/lints/grille_window_stacking.yml#L2-L5

### Why is this bad/What are the consequences?

This can cause issues with admin events, expressly excluding maps from maplint checks should be avoided.

### Steps to reproduce the issue.

Start a server and the game. After the game is started, go to a space z-level and dynamically load moonoutpost19.dmm. Observe many objects moving from their original placement. A good spot to notice this are these rooms:

2024_08_03__11_37_06__paradise dme  moonoutpost19 dmm  - StrongDMM
2024_08_03__11_37_13__Paradise Station 13

### When did the problem start happening?

Post-MILLA.

### Extra information

_No response_

### Relevant log output/runtime error

_No response_

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do

Adds z-level atmos freezing to MILLA, specifically for when loading maps. This also bumps up `MAX_Z_LEVELS` in rust, as there may be more than normal z-levels now with #28101. Waiting on #28101 to be merged first.

## Why It's Good For The Game

Fixes #26385

## Testing

Yes, it works.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
<hr>

## Changelog

NPFC

### CODE REVIEW

**Comment by Contrabang** [comment]
!build_rust

**Comment by Contrabang** [comment]
!build_rust

File: rust/src/milla/constants.rs [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /// How many Z levels we allow before being suspicious that the wrong number was sent.
-pub(crate) const MAX_Z_LEVELS: i32 = 10;
+pub(crate) const MAX_Z_LEVELS: i32 = 12;
```
Comment (FunnyMan3595) [inline rust/src/milla/constants.rs:2]: I'd push it to at least 15 if not 20. This is a safety net, not a leash.

File: rust/src/milla/api.rs [hunk 2]
```diff
@@ -703,6 +703,27 @@ fn milla_get_tick_time() -> eyre::Result<ByondValue> {
...
+    let active = buffers.get_active().read().unwrap();
+    let maybe_z_level = active.0[z as usize].try_write();
+    if maybe_z_level.is_err() {
+        return Err(eyre!(
+            "Tried to freeze during asynchronous, read-only atmos. Use a /datum/milla_safe/..."
+        ));
+    }
+    let mut z_level = maybe_z_level.unwrap();
+    let frozen = bool::try_from(byond_frozen)?;
+    z_level.frozen = frozen;
```
Comment (FunnyMan3595) [inline rust/src/milla/api.rs:723]:
```suggestion
    let z = f32::try_from(byond_z)? as i32 - 1;
    let frozen = bool::try_from(byond_frozen)?;
    let buffers = BUFFERS.get().ok_or(eyre!("BUFFERS not initialized."))?;
    let active = buffers.get_active().read().unwrap();
    let maybe_z_level = active.0[z as usize].try_write();
    if maybe_z_level.is_err() {
        return Err(eyre!(
            "Tried to freeze or unfreeze during asynchronous, read-only atmos. Use a /datum/milla_safe/..."
        ));
    }
    let mut z_level = maybe_z_level.unwrap();
    z_level.frozen = frozen;
```

**Review by FunnyMan3595 — CHANGES_REQUESTED** [review]
You need to add `frozen` to `ZLevel`'s `copy_from` method, or you'll only update one of the two buffers, which is bad in both directions.

Smaller stuff inline.

**Comment by Contrabang** [comment]
!build_rust

**Comment by Contrabang** [comment]
!build_rust

**Comment by Contrabang** [comment]
!build_rust

**Review by FunnyMan3595 — APPROVED** [review]

**Review by AffectedArc07 — APPROVED** [review]
Go go gadget merge tool
