### PR TITLE
Minor fixes: Cmd. amplification, nitroglycerin reagent

### LINKED ISSUE #13365: Highlight words bugs out when examining thing with said word in the Name
**Issue Description**: Highlight words bugs out when examining thing with said word in the Name

I have hightlighted the word "atmos" (without " "). Everytime I examine someone wearing an atmospherics jumpsuit I get a long string of letters starting with src="data:image..."

**What did you expect to happen**:  I examined a person wearing an atmos jumpsuit

I expected to see the symbol of the atmospheric thechicians jumpsuit and not some weird long line of text.

**What happened instead**:

Example of examining an assistant wearing a atmospheric technicians jumpsuit:

This is Orchid Of The Stars, a diona!
He is wearing atmos" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAPFBMVEXAwMCWcgDGlgCrq6vMmwDZ2dn/2wIAbZEAlMEAqf+MjIxUVFRra2vDlQADTmY8PDyBgYHAwMCnfwB8XQBGIXzjAAAAAXRSTlMAQObYZgAAAGR6VFh0RGVzY3JpcHRpb24AAHicU1ZwcnX39FNw8fXkKkstKs7Mz1OwVTDRM+DiLM9MKckAcoyNuDgzUjPTM0ognOKSxJJUIFNJiYszJbOoGMg05OJMK0rMTYWwlRVc/VzAJgIAmrcYC32rgUMAAACESURBVDiN7dDLDsQgCAVQwApSH+3o///rQJcTWc22NyEu7gkmALz5DRKllIgw6o8Dc8r+BICZMCMx74EUdmE9F9kCdXGyatEAiIFqQPYAxEGzkX3vO1SbTdSD9GcDhQukdwNE0Rfjqu3+3K1eIwAy5yQbCYHdEO2eEYCxFk5cK+rf/JUvKBYEicXF9J4AAAAASUVORK5CYII="> a blood-stained atmospheric technician's jumpsuit!
He is wearing  a blood-stained hair flower pin on his head!
He has  a leather satchel on his back.
He has blood-stained hands!
He has  a tool-belt about his waist.
He is wearing  some blood-stained work boots on his feet!
He has  an engineering radio headset on his left ear.
He is wearing  Orchid Of The Stars's ID Card (Civilian).
He is limp and unresponsive; there are no signs of life...
He has severe bruising!
He has severe burns!
He is bleeding!

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:

Set hightlight string to "atmos" without (" ")
I have set regex to: on

**When did the problem start happening**:
Constantly, always

**Extra information**:

### LINKED ISSUE #13493: Nitroglycerin reagent 'missing' for adding to plants
**Issue Description**:

Not sure how specific this bug is, but, the server log is stating:

```
##DEBUG: Explosion(194,87,1)(d-1,h0,l1): Took 0 seconds.
##WARNING: The patch of peanuts attempted to add a reagent called 'nitroglycerin' which doesn't exist. ()
```

Despite nitro apparently not existing, it still explodes effectively.
**What did you expect to happen**: 

Its basically working as expected but the warning makes me think there may be more going on.

**What happened instead**:

Everything is functioning as expected except for the server warning message.

**Why is this bad/What are the consequences**:

On its own it seems harmless but definitely seems unintended.

**Steps to reproduce the problem**:

I was privately testing nitroglycerin plants, used peanuts for a base, var-edited the seeds for yield/potency and added traits extracted from spawned seeds.

**When did the problem start happening**:

First time I've noticed it.

**Extra information**:

This may or may not be issue worthy, as it doesn't really affect anything, but definitely feels like its at least displaying an unintended warning.

Also nitro plants are pretty badass.
image

### LINKED ISSUE #13499: Command say speech gets bold when they speak into the radio
**Issue Description**:
The say to_chat after a command member talks into the comms gets made bold. Not just the comms line.

**What did you expect to happen**: 
Them to not speak up loudly (not to get bold say text)

**What happened instead**:
image

**Why is this bad/What are the consequences**:
It's a bug or unlisted feature

**Steps to reproduce the problem**:
Talk into comms as command with tcomms set up

**When did the problem start happening**:
After #13446

### PR DESCRIPTION
**Pull request by dearmochi**
## What Does This PR Do
Fixes #13499: Make a copy of `message_pieces` when instancing message datum for radio speech to allow editing the radio line without affecting the non-radio line.

Fixes #13493: Clear the `result` field for the nitroglycerin chemical reaction.

~~Fixes #13365: Rework highlight regex replacement logic to not touch HTML code anymore, only plain text.~~

## Why It's Good For The Game
The non-comms line is no longer bolded and now appears as it did before #13446. Heads of staff no longer sound like they're yelling (even if no actual amplification took place physically).

The nitroglycerin fix is mostly for server operators: no log complaining about the nitroglycerin reagent being non-existing will show up anymore.

~~Highlighting words with regex now works properly and doesn't break HTML anymore, no longer resulting in horribly mangled messages.~~

## Changelog
:cl:
fix: TComms message handling no longer affects non-comms line
fix: Nitroglycerin chemical reaction no longer yields (non-existent) reagent
/:cl:

### CODE REVIEW

**Comment by SteelSlayer** [comment]
There is another dedicated regex fix PR up: #12690. I don't know which one is the more "proper" one, because I don't know much about regex but, just thought I'd let you know.

File: goon/browserassets/js/browserOutput.js [hunk 1]
```diff
@@ -176,20 +176,47 @@ function highlightTerms(el) {
...
+				if (child.nodeType != Node.TEXT_NODE) {
+					if (child.className != "highlighted")
+						highlightTerms(child);
+					continue;
+				}
+					
+				var tx = child.textContent;
+
+				var index = tx.toLowerCase().indexOf(term.toLowerCase());
+				if (index > -1) {
```
Comment (farie82) [inline goon/browserassets/js/browserOutput.js:206]: This won't highlight multiple matches right? So if you highlight "ai" and you have the sentence "AI open the door or I'll kill myself AI. Law 1 AI". Will it match all 3 of those?

Comment (dearmochi) [reply goon/browserassets/js/browserOutput.js:206]: Looks like it does, but it doesn't keep the case on the highlighted stuff:

image

I'll push a fix for that shortly

Comment (farie82) [reply goon/browserassets/js/browserOutput.js:206]: No this one does what I expect it to do. Except for the casing ofcourse. Thanks for testing!
I also now see how it goes right. It creates a new element for the words behind and thus those will also be checked in the DOM loop

**Comment by craftxbox** [comment]
hi! i'm not a maintainer, but generally, you should make pr's atomically, as it makes it confusing for conflicting pr's.
I have a pr open, #12690 that fixes the regex issues already (as i made the regex feature originally), I'd appreciate it if you could have a look at that and comment on anything you've done differently there.

File: code/modules/reagents/chemistry/recipes/pyrotechnics.dm [hunk 2]
```diff
@@ -56,7 +56,7 @@
 /datum/chemical_reaction/nitroglycerin
 	name = "Nitroglycerin"
 	id = "nitroglycerin"
-	result = "nitroglycerin"
+	result = null
```
Comment (AffectedArc07) [inline code/modules/reagents/chemistry/recipes/pyrotechnics.dm:59]: Tested PR locally and it works, but please remove this line since it defaults to a null result
```dm
/datum/chemical_reaction
	var/name = null
	var/id = null
	var/result = null
```

Comment (dearmochi) [reply code/modules/reagents/chemistry/recipes/pyrotechnics.dm:59]: done
