### PR TITLE
[TGUI] Implant Pad + Implanter Related Sprites + Slight Implant refactor

### LINKED ISSUE #18693: Labor Points Console broken since TGUI merge
**Issue Description**:
The new labor camp points manager with TGUI is broken for sec - who can no longer log on to them to use their tracker function.

**What did you expect to happen**: 
I expected to be able to log onto the new console much in the same wait as the sec logs console.

**What happened instead**:
When you try to insert your ID to log on, you just hit your ID on it. You cannot log on without the ID being in the machine.

**Why is this bad/What are the consequences**:
Sec can no longer track perma inmates/parolees.

**Steps to reproduce the problem**:
As warden attempted to log onto the new console. The 'log on' button was greyed out. Tried to insert ID into machine as normal but just hit the machine with it and was unable to get it to insert.

**When did the problem start happening**:
The problem happened when the labor points console TGUI PR was merged.

**Extra information**:
N/A

### PR DESCRIPTION
**Pull request by Sirryan2002**
## What Does This PR Do
Does a few things

1.  Adds new sprites for implant cases, the implant pad, and implanters
-Implant Pad + Case Sprite are of my own work
-New Implanters were sprited in [TG Station #66722](https://github.com/tgstation/tgstation/pull/66722) by [PestoVerde322](https://github.com/PestoVerde322)
2. Refactors Implant Code, mostly all just cleanup, implantpad had a few changes, also put an autosurgeon sprite as the base implant icon state so that it's not broken in-game (I know this is "sprite debt" but broken icons cause significant client lag upon examination/display)
3. Removes the ID var on tracking implants as they did absolute jack shit
4. Ensures all Implants have implanters and implant cases defined in the code
5. Ports the Implantpad to TGUI
6. Fixes #18693
## Why It's Good For The Game
Sometimes you just need to update some crusty ass sprites that have outlived their time period. Also it's nice to have more code brought up to modern styling standards. 

Project Progression -> #18493 and #14968
## Images of changes
<details><summary> Lovely Images</summary>

ImplantCompare

padnocase

padcasenoimplant

padimplant

padimplant2

</details>

## Next things on my shitlist after this PR

1.  Implant Chair
2. Locater

## Changelog
:cl:
add: Adds implanters + implant cases for every implanter implant available
del: Removed ID setter on implantpad
tweak: Implant Pad is now TGUI instead of browserUI
imageadd: Implant Cases have new sprites
imageadd: Implanters have new sprites
/:cl:

### CODE REVIEW

File: tgui/packages/tgui/interfaces/ImplantPad.js [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+                  style={{
+                    'vertical-align': 'middle',
+                    width: '32px',
+                  }}/>
+                  {implant.name}
+                </Box>
+                <LabeledList>
+                  <LabeledListItem label="life">{implant.life}</LabeledListItem>
+                  <LabeledListItem label="notes">{implant.notes}</LabeledListItem>
+                  <LabeledListItem label="function">{implant.function}</LabeledListItem>
```
Comment (CinnamonSnowball) [inline tgui/packages/tgui/interfaces/ImplantPad.js:30]: Tiny nitpick
```suggestion
                  <LabeledListItem label="Life">{implant.life}</LabeledListItem>
                  <LabeledListItem label="Notes">{implant.notes}</LabeledListItem>
                  <LabeledListItem label="Function">{implant.function}</LabeledListItem>
```

**Comment by S34NW** [comment]
This might be out of scope, but could we perhaps rename these from "implants" to differentiate from the surgery-implanted implants? (eye-shield, nodrop, CNS, etc.)

**Comment by Sirryan2002** [comment]
> This might be out of scope, but could we perhaps rename these from "implants" to differentiate from the surgery-implanted implants? (eye-shield, nodrop, CNS, etc.)

I really don't want to up the files changed on this PR by 30 files + a couple mad edits

**Comment by S34NW** [comment]
You could, for example, call them "microchips" or something

File: code/game/objects/items/weapons/implants/implant.dm [hunk 2]
```diff
@@ -26,22 +26,25 @@
 /obj/item/implant
 	name = "implant"
 	icon = 'icons/obj/implants.dmi'
-	icon_state = "generic" //Shows up as the action button icon
+	icon_state = "generic" //Shows up as a auto surgeon, used as a placeholder when a implant doesn't have a sprite
 	origin_tech = "materials=2;biotech=3;programming=2"
-
 	actions_types = list(/datum/action/item_action/hands_free/activate)
+	item_color = "b"
```
Comment (moxian) [inline code/game/objects/items/weapons/implants/implant.dm:32]: 🅱️ ?

File: code/game/objects/items/weapons/implants/implant.dm [hunk 3]
```diff
@@ -50,6 +53,9 @@
 	/// Whether this implant has already triggered on death or not, to prevent it firing multiple times.
 	var/has_triggered_on_death = FALSE
 
+	///the implant_fluff datum attached to this implant, purely cosmetic "lore" information
+	var/datum/implant_fluff/implant_data = new()
```
Comment (moxian) [inline code/game/objects/items/weapons/implants/implant.dm:57]:
```dm
	var/datum/implant_fluff/implant_data = /datum/implant_fluff
```
 instead of `=new()` and instantiate it in the Initialize(). i.e.
```dm
/Initialize(mapload)
  . = ..()
  if(ispath(implant_data)) implant_data = new implant_data
```

File: code/game/objects/items/weapons/implants/implantfluff.dm [hunk 4]
```diff
@@ -0,0 +1,114 @@
+
+/**
+ * # Implant Fluff Datum
+ *
+ * All implants have used to have a get_data() call which used to return html, this datum serves to better method to
```
Comment (moxian) [inline code/game/objects/items/weapons/implants/implantfluff.dm:5]: nobody cares about how terrible the system used to be when reading doc comments

File: code/game/objects/items/weapons/implants/implantfluff.dm [hunk 5]
```diff
@@ -0,0 +1,114 @@
...
+/datum/implant_fluff
+	var/name = "Unknown Implant"
+	var/life = "Not Specified"
+	var/notes = "No Notes"
+	var/function = "An electronic insert that supplements biological functions"
+
+/datum/implant_fluff/abductor
+	name = "GC$X9%D#G"
+	life = "Unknown"
+	notes = "Appears to contain highly advanced bluespace technology"
```
Comment (moxian) [inline code/game/objects/items/weapons/implants/implantfluff.dm:19]: I think it's slightly better to have these fluff datums right next to corresponding implant, rather than in this one file. But it's whatever

File: code/game/objects/items/weapons/implants/implant.dm (hunk 2 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implant.dm:32]: old code moment, I'll see what the consequences of removing this is, although there should be none.

File: code/game/objects/items/weapons/implants/implant.dm (hunk 3 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implant.dm:57]: sounds good

**Comment by Sirryan2002** [comment]
after some review, I'm going to add a labeling system to tracking implants so that A) the implantpad has non-fluff functionality and B) so that tracking implants have unique identifiers in the locator (once that is TGUI'd of course)

**Comment by Sirryan2002** [comment]
will try and get to this soonish

File: code/game/objects/items/weapons/implants/implantfluff.dm (hunk 4 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implantfluff.dm:5]: removed

File: code/game/objects/items/weapons/implants/implant.dm (hunk 3 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implant.dm:57]: added

File: code/game/objects/items/weapons/implants/implant.dm (hunk 2 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implant.dm:32]: changed to "black"

File: code/game/objects/items/weapons/implants/implant.dm [hunk 6]
```diff
@@ -50,6 +53,13 @@
 	/// Whether this implant has already triggered on death or not, to prevent it firing multiple times.
 	var/has_triggered_on_death = FALSE
 
+	///the implant_fluff datum attached to this implant, purely cosmetic "lore" information
+	var/datum/implant_fluff/implant_data = /datum/implant_fluff
+
+/obj/item/implant/Initialize(mapload)
+	. = ..()
+	if(ispath(implant_data)) implant_data = new implant_data
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implant.dm:61]:
```suggestion
	if(ispath(implant_data)) 
		implant_data = new implant_data
```

File: code/game/objects/items/weapons/implants/implant_adrenalin.dm [hunk 7]
```diff
@@ -0,0 +1,39 @@
...
+	imp_in.SetKnockDown(0)
+	imp_in.SetParalysis(0)
+	imp_in.adjustStaminaLoss(-75)
+	imp_in.stand_up(TRUE)
+
+	imp_in.reagents.add_reagent("synaptizine", 10)
+	imp_in.reagents.add_reagent("omnizine", 10)
+	imp_in.reagents.add_reagent("stimulative_agent", 10)
+	if(!uses)
+		qdel(src)
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implant_adrenalin.dm:24]: Does this remove it from the user or just leave them with a null item inside? I'm not entirely unconvinced that this might be causing some issues with implant checks.

File: code/game/objects/items/weapons/implants/implant_death_alarm.dm [hunk 8]
```diff
@@ -59,5 +50,20 @@
...
+
+/obj/item/implanter/death_alarm
+	name = "implanter (Death Alarm)"
+
+/obj/item/implanter/death_alarm/Initialize(mapload)
+	imp = new /obj/item/implant/death_alarm(src)
+	..()
+
+/obj/item/implantcase/death_alarm
+	name = "Glass Case- 'Death Alarm'"
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implant_death_alarm.dm:64]: Any reason this one's a "Glass Case" while the abductor one is an "Implant Case"?

Also, spacing on the hyphen.

File: code/game/objects/items/weapons/implants/implant_dust.dm [hunk 9]
```diff
@@ -0,0 +1,46 @@
+// Dust implant, for CC officers. Prevents gear theft if they die.
+
+/obj/item/implant/dust
+	name = "duster implant"
+	desc = "An alarm which monitors host vital signs, transmitting a radio message and dusting the corpse on death."
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implant_dust.dm:5]: What's the radio message bit about?

File: code/game/objects/items/weapons/implants/implantcase.dm [hunk 10]
```diff
@@ -54,45 +55,6 @@
 				update_state()
 			I.update_icon(UPDATE_ICON_STATE)
 
-	/*else if(istype(W, /obj/item/ammo_casing/shotgun/implanter))
-		var/obj/item/ammo_casing/shotgun/implanter/I = W
-		if(I.implanter)
-			src.attackby(I.implanter, user, params) */ // COMING SOON -- c0
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implantcase.dm:60]: coming soon...

this would have been pretty damn cool, if not incredibly overpowered. Mindshield implant slugs.

File: code/game/objects/items/weapons/implants/implantfluff.dm [hunk 11]
```diff
@@ -0,0 +1,112 @@
...
+/**
+ * # Implant Fluff Datum
+ *
+ * Implant fluff is just lore about the implant that is accessed through the implantpad, you must attach
+ * one of these datums to the implant_data var on an implant for it to show it up.
+ */
+/datum/implant_fluff
+	var/name = "Unknown Implant"
+	var/life = "Not Specified"
+	var/notes = "No Notes"
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implantfluff.dm:11]: You might want to make sure everything in here has periods where they need it. Especially since these are all fluff.

File: code/game/objects/items/weapons/implants/implantfluff.dm [hunk 12]
```diff
@@ -0,0 +1,112 @@
...
+	var/function = "An electronic insert that supplements biological functions"
+
+/datum/implant_fluff/abductor
+	name = "GC$X9%D#G"
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implantfluff.dm:15]: Wonder if it'd be possible to make this use wingdings like grey speech?

File: code/game/objects/items/weapons/implants/implantfluff.dm [hunk 13]
```diff
@@ -0,0 +1,112 @@
...
+/datum/implant_fluff/explosive
+	name = "Cybersun Industries RX-78 Employee Management Implant"
+	life = "Destroyed upon activation"
+	notes = "Appears to contain a small, dense explosive device wired to a signaller chip, the serial number on the side is scratched out."
+	function = "Contains a compact, electrically detonated explosive that detonates upon receiving a specially encoded signal or upon host death."
+
+/datum/implant_fluff/explosive_macro
+	name = "Cybersun Industries RX-79 Employee Management Implant"
+	life = "Destroyed upon activation"
+	notes = "Compared to it's predecessor (the RX-78) contains a much larger explosive, sometimes you just need a bigger boom. Due to its bulkiness, it has be known to press into the user's frontal lobe, impairing judgement."
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implantfluff.dm:63]:
```suggestion
	notes = "Compared to its predecessor, the RX-79 contains a much larger explosive; sometimes you just need a bigger boom. Due to its bulkiness, it has been known to press into the user's frontal lobe, impairing judgement."
```

File: code/game/objects/items/weapons/implants/implantfluff.dm [hunk 14]
```diff
@@ -0,0 +1,112 @@
...
+	function = "Contains a bulky, electrically detonated explosive that detonates upon receiving a specially encoded signal or upon host death."
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implantfluff.dm:64]:
```suggestion
	function = "Contains a bulky, electrically triggered explosive that detonates upon receiving a specially encoded signal or upon host death."
```

File: code/game/objects/items/weapons/implants/implantfluff.dm [hunk 15]
```diff
@@ -0,0 +1,112 @@
...
+
+/datum/implant_fluff/freedom
+	name = "Cybersun Industries RX-92 Quick Escape Implant"
+	life = "Destroyed after 4 uses"
+	notes = "An implant that is illegal in many systems. It is notoriously known for allowing users to grotesquely fracture bones and over-exert joints in order to slip out of the tightest of restraints."
+	function = "Uses a mixture of cybernetic nanobots, bone regrowth chemicals, and radio signals to quickly break the user out of restrains"
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implantfluff.dm:70]:
```suggestion
	function = "Uses a mixture of cybernetic nanobots, bone regrowth chemicals, and radio signals to quickly break the user out of restraints."
```

File: code/game/objects/items/weapons/implants/implantfluff.dm [hunk 16]
```diff
@@ -0,0 +1,112 @@
...
+
+/datum/implant_fluff/storage
+	name = "Cybersun Industries RX-16 Collapsible Body Cavity Implant"
+	notes = "Prolonged usage of this implant often results in the users bones being fractured and occassionaly complete organ failure."
+	function = "Allows the user to store two small objects within a cybernetic body cavity."
+
+/datum/implant_fluff/tracking
+	name = "Nanotrasen RFID Tracking Chip"
+	life = "Unknown, known to last up to a few years"
+	notes = "Tracking implants are Neuro-safe! It uses Specialized shell that will melt and disintegrate into bio-safe elements if it ever malfunctions. "
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implantfluff.dm:95]:
```suggestion
	notes = "Tracking implants are Neuro-safe! Makes use of a specialized shell that will melt and disintegrate into bio-safe elements in the event of a malfunction. "
```

File: code/game/objects/items/weapons/implants/implantfluff.dm [hunk 17]
```diff
@@ -0,0 +1,112 @@
...
+	function = "Continuously transmits low power signal. Can be used for tracking and teleporting to the user."
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implantfluff.dm:96]:
```suggestion
	function = "Continuously transmits a low power signal. Can be used for tracking and teleporting to the user."
```

File: code/game/objects/items/weapons/implants/implantfluff.dm [hunk 18]
```diff
@@ -0,0 +1,112 @@
...
+/datum/implant_fluff/traitor
+	name = "Syndicate Type E Mindslave Implant"
+	life = "Unknown, no collected sample has been active long enough to determine lifespan"
+	notes = "Any humanoid injected with this implant will become loyal to the injector, unless of course the host is already loyal to someone else. It's Diplomacy made easy. The Syndicate is known to use this for political and diplomatic leverage."
+	function = " Contains a small pod of nanobots that manipulate the host's mental functions and slave the host to the implanter."
+
+/datum/implant_fluff/uplink
+	name = "Syndicate Agent Uplink Implant"
+	life = "Unknown, no collected sample has been active long enough to determine lifespan"
+	notes = "An intricate piece of machinery that interfaces directly with the users brain and which inner workings area a closely guarded syndicate secret."
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implantfluff.dm:107]:
```suggestion
	notes = "An intricate piece of machinery that interfaces directly with the users brain and which inner workings are a closely guarded syndicate secret."
```

File: code/game/objects/items/weapons/implants/implantfluff.dm [hunk 19]
```diff
@@ -0,0 +1,112 @@
...
+	function = "Allows the user to access a syndicate uplink connected contained within their body, invisible to the outside but provides the same functionality as a regular uplink."
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implantfluff.dm:108]:
```suggestion
	function = "Allows the user to access a syndicate uplink connected contained within their body, invisible to the outside but providing the same functionality as a regular uplink."
```

File: code/game/objects/items/weapons/implants/implantfluff.dm [hunk 20]
```diff
@@ -0,0 +1,112 @@
...
+
+/datum/implant_fluff/sad_trombone
+	name = "BioTech Solution Comedy Implant"
+	function = "Plays a Sad Trombone noise upon death of the implantee, allows clowns to entertain the crew even in the post-mordem"
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implantfluff.dm:112]:
```suggestion
	function = "Plays a sad trombone noise upon death of the implantee, allows clowns to entertain the crew even post-mortem."
```

File: code/game/objects/items/weapons/implants/implantfluff.dm [hunk 21]
```diff
@@ -0,0 +1,112 @@
...
+	function = " Contains a small pod of nanobots that manipulate the host's mental functions and slave the host to the implanter."
+
+/datum/implant_fluff/uplink
+	name = "Syndicate Agent Uplink Implant"
+	life = "Unknown, no collected sample has been active long enough to determine lifespan"
+	notes = "An intricate piece of machinery that interfaces directly with the users brain and which inner workings area a closely guarded syndicate secret."
+	function = "Allows the user to access a syndicate uplink connected contained within their body, invisible to the outside but provides the same functionality as a regular uplink."
+
+/datum/implant_fluff/sad_trombone
+	name = "BioTech Solution Comedy Implant"
```
Comment (lewcc) [inline code/game/objects/items/weapons/implants/implantfluff.dm:111]: Some of these fluff messages say Biotech Solution, some of them say Biotech Solutions. Probably want to standardize it.

**Review by lewcc — COMMENTED** [review]
Mostly nits, especially some of the stuff with the fluff. Looks good in general.

File: code/game/objects/items/weapons/implants/implant_adrenalin.dm (hunk 7 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implant_adrenalin.dm:24]: I have no idea, I just moved this to a completely new file, all of this is OG code from before this PR. It's entirely possible that there is a ref list that includes this implant somewhere and there isn't a signal registered on the implant to listen to see if it's QDEL'd

File: code/game/objects/items/weapons/implants/implant_death_alarm.dm (hunk 8 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implant_death_alarm.dm:64]: erghh, old code. I'll double check all of them for consistency and ensure they're all implant case

File: code/game/objects/items/weapons/implants/implant_dust.dm (hunk 9 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implant_dust.dm:5]: no idea, old code. Will correct it.

File: code/game/objects/items/weapons/implants/implantfluff.dm (hunk 11 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implantfluff.dm:11]: 👍 will do

File: code/game/objects/items/weapons/implants/implantfluff.dm (hunk 19 above)
Comment (S34NW) [reply code/game/objects/items/weapons/implants/implantfluff.dm:108]:
```suggestion
	function = "Allows the user to access a syndicate uplink connected contained within their body, invisible from the outside but provides the same functionality as a regular uplink."
```

File: code/game/objects/items/weapons/implants/implant_adrenalin.dm (hunk 7 above)
Comment (lewcc) [reply code/game/objects/items/weapons/implants/implant_adrenalin.dm:24]: Gotcha. I've been suspecting recently that the reason implant checks sometimes seem to need to be done multiple times may have a few causes: the fact that it has no fail step, meaning no message is displayed if it fails (which I'm trying to address in my PR), and the possibility that it is finding a null/expired implant inside the body.

**Comment by Sirryan2002** [comment]
Will have requested changes done in the next 3-4 days. Currently dealing with a 40 hour work week 💀

**Review by SteelSlayer — CHANGES_REQUESTED** [review]
Partial review for now.

I didn't want spam suggestions for calling `. = ..()` at the start of `Initialize()`, but can you could please go over all the places where you changed `/New` to `/Initialize` and make that change?

File: code/game/machinery/computer/prisoner.dm [hunk 22]
```diff
@@ -161,12 +164,12 @@
...
 					if(implant.imp_in)
 						var/mob/living/carbon/implantee = implant.imp_in
-						var/warning = copytext(sanitize(text2num(answer)), 1, MAX_MESSAGE_LEN)
+						var/warning = copytext(sanitize(answer), 1, MAX_MESSAGE_LEN)
 						to_chat(implantee, "<span class='boldnotice'>Your skull vibrates violently as a loud announcement is broadcasted to you: '[warning]'</span>")
 				if("set_points")
 					if(isnull(text2num(answer)))
 						return
-					inserted_id.goal = max(text2num(answer), 0)
+					inserted_id.goal = clamp(text2num(answer), 0, 50000)
```
Comment (S34NW) [inline code/game/machinery/computer/prisoner.dm:172]:
```suggestion
					inserted_id.goal = clamp(text2num(answer), 0, 9000)
```
this limit is 5000 not 50000 according to SoP, that equates to about 33 minutes roughly. Perhaps it should be changed to 9000, which is closer to 60 minutes

File: code/game/objects/items/weapons/implants/implantcase.dm (hunk 10 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implantcase.dm:60]: adressed

File: code/game/objects/items/weapons/implants/implant_death_alarm.dm (hunk 8 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implant_death_alarm.dm:64]: adressed

File: code/game/objects/items/weapons/implants/implantfluff.dm (hunk 12 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implantfluff.dm:15]: It would be cool, but also I'd have to add in custom TGUI behavior to set the font to wing dings, which is pretty doable but I'm also getting ready to move back in for college and I'm exhausted.

File: code/game/objects/items/weapons/implants/implantfluff.dm (hunk 21 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implantfluff.dm:111]: fixed

File: code/game/machinery/computer/prisoner.dm [hunk 23]
```diff
@@ -161,12 +164,12 @@
 					implant.warn_cooldown = world.time + IMPLANT_WARN_COOLDOWN
 					if(implant.imp_in)
 						var/mob/living/carbon/implantee = implant.imp_in
-						var/warning = copytext(sanitize(text2num(answer)), 1, MAX_MESSAGE_LEN)
```
[the remark this answers is not in the document]
Comment (Sirryan2002) [reply code/game/machinery/computer/prisoner.dm:164]: it's not a number anymore, it's supposed to just be a string of text.

File: code/game/machinery/computer/prisoner.dm (hunk 22 above)
Comment (Sirryan2002) [reply code/game/machinery/computer/prisoner.dm:172]: This is a good point. I've set it to 20,000 which will cap the amount at around 2 hours and added comments for my justification for this cap.

**Comment by Sirryan2002** [comment]
still need to fix issues with uplink implants due to conflicts

**Comment by Sirryan2002** [comment]
I promise I'm not forgetting about this PR, just working through early university setup stuff atm

File: code/game/objects/items/weapons/implants/implant.dm [hunk 24]
```diff
@@ -50,6 +53,14 @@
 	/// Whether this implant has already triggered on death or not, to prevent it firing multiple times.
 	var/has_triggered_on_death = FALSE
 
+	///the implant_fluff datum attached to this implant, purely cosmetic "lore" information
+	var/datum/implant_fluff/implant_data = /datum/implant_fluff
+
+/obj/item/implant/Initialize(mapload)
+	. = ..()
+	if(ispath(implant_data)) 
+		implant_data = new implant_data
```
Comment (hal9000PR) [inline code/game/objects/items/weapons/implants/implant.dm:62]: this needs to be nulled out on destroy.

File: code/game/objects/items/weapons/implants/implantcase.dm [hunk 25]
```diff
@@ -1,16 +1,17 @@
...
 	throw_speed = 2
 	throw_range = 5
 	w_class = WEIGHT_CLASS_TINY
 	origin_tech = "materials=1;biotech=2"
 	container_type = OPENCONTAINER | INJECTABLE | DRAWABLE
-	materials = list(MAT_GLASS=500)
-	var/obj/item/implant/imp = null
+	materials = list(MAT_GLASS = 500)
+
+	var/obj/item/implant/imp
```
Comment (hal9000PR) [inline code/game/objects/items/weapons/implants/implantcase.dm:14]: needs nulling out on destroy, probably `QDEL_NULL`

File: code/game/objects/items/weapons/implants/implantchair.dm [hunk 26]
```diff
@@ -126,7 +126,7 @@
 
 
 /obj/machinery/implantchair/proc/add_implants()
-	for(var/i=0, i<src.max_implants, i++)
+	for(var/i = 0, i< max_implants, i++)
 		var/obj/item/implant/mindshield/I = new /obj/item/implant/mindshield(src)
 		implant_list += I
 	return
```
Comment (hal9000PR) [inline code/game/objects/items/weapons/implants/implantchair.dm:132]: dangling return

File: code/game/objects/items/weapons/implants/implantchair.dm [hunk 27]
```diff
@@ -126,7 +126,7 @@
 
 
 /obj/machinery/implantchair/proc/add_implants()
-	for(var/i=0, i<src.max_implants, i++)
+	for(var/i = 0, i< max_implants, i++)
 		var/obj/item/implant/mindshield/I = new /obj/item/implant/mindshield(src)
 		implant_list += I
```
Comment (hal9000PR) [inline code/game/objects/items/weapons/implants/implantchair.dm:131]: would you make this for loop use the `var/i in 1 to max_implants` syntax

**Review by hal9000PR — CHANGES_REQUESTED** [review]
this + steels comments please.

File: code/game/objects/items/weapons/implants/implantchair.dm (hunk 27 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implantchair.dm]: done

File: code/game/objects/items/weapons/implants/implantchair.dm (hunk 26 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implantchair.dm]: removed

File: code/game/objects/items/weapons/implants/implantcase.dm (hunk 25 above)
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implantcase.dm:14]: done

**Review by hal9000PR — APPROVED** [review]

File: tgui/packages/tgui/interfaces/PrisonerImplantManager.js [hunk 28]
```diff
@@ -76,7 +76,7 @@ export const PrisonerImplantManager = (props, context) => {
           {trackingInfo
             .map(implant => (
               <>
-                <Box bold>Subject: {implant.subject}</Box><Box key={implant.id}>
+                <Box bold>Subject: {implant.subject}</Box><Box key={implant.subject}>
```
Comment (SteelSlayer) [inline tgui/packages/tgui/interfaces/PrisonerImplantManager.js:79]: Why this change here?

File: code/game/objects/items/weapons/implants/implant_abductor.dm [hunk 29]
```diff
@@ -2,20 +2,23 @@
 	name = "recall implant"
 	desc = "Returns you to the mothership."
 	icon = 'icons/obj/abductor.dmi'
-	icon_state = "implant"
+	icon_state = "implant" //ew
```
[the remark this answers is not in the document]
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implant_abductor.dm:5]: because the way the icon for this implant is handled is weird

File: tgui/packages/tgui/interfaces/PrisonerImplantManager.js (hunk 28 above)
Comment (Sirryan2002) [reply tgui/packages/tgui/interfaces/PrisonerImplantManager.js:79]: I removed the id var from the implant list.

File: code/game/objects/items/weapons/implants/implant_uplink.dm [hunk 30]
```diff
@@ -4,54 +4,64 @@
...
+/obj/item/implant/uplink/nuclear/Initialize(mapload)
+	. = ..()
+	if(hidden_uplink)
+		hidden_uplink.update_uplink_type(UPLINK_TYPE_NUCLEAR)
+
+/obj/item/implanter/nuclear
+	name = "implanter (Nuclear Agent Uplink)"
+
+/obj/item/implanter/nuclear/Initialize(mapload)
+	. = ..()
```
[the remark this answers is not in the document]
Comment (Sirryan2002) [reply code/game/objects/items/weapons/implants/implant_uplink.dm:55]: I was going to do that, but the parent intialize will set `imp`  again

**Review by SteelSlayer — APPROVED** [review]
